name: Node.js CI

on:
  push:

env:
  MONGO_URL_TEST: mongodb://localhost/testdb
  ACCESS_TOKEN_SECRET: somesecret

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0

      - run: npm ci
      - run: npm test
