name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGO_URL_TEST: mongodb://localhost/testdb
  ACCESS_TOKEN_SECRET: somesecret

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0

      - run: npm ci
      - run: npm test
      - name: upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage report
          path: coverage/

      # - run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "judoincloud-backend"
          heroku_email: "alessandro.girardi-2@studenti.unitn.it"
